Fixing Linux-only link tinfo to LLVM-5.0 (at least for now).
Was getting the error:

    /usr/bin/ld: /usr/lib/libLLVMSupport.a(Process.cpp.o): undefined reference to symbol 'set_curterm'
    /usr/lib/libtinfo.so.6: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

But after adding it, running oolong resulted in:

    : CommandLine Error: Option 'disable-symbolication' registered more than once!
    LLVM ERROR: inconsistency in registered CommandLine options

Changing tinfo to LLVM-5.0 works, though I'm not exactly sure what's going on
or what the ultimate conflict is.  Since this works I'm leaving it until it
becomes an issue in the future.